### ISSUE TITLE
Crafted an iron-capped stick wand, issues abound.

### ISSUE THREAD

**Issue by Febilian** [Shadows-of-Fire/Magic-Theory-2#2]
I honestly do not know what happened, but as soon as I picked up the wand I'd crafted, I was completely unable to move or open my inventory. I could look around and whatnot, and I dropped the wand to see if it had a correlation but didn't fix it completely(I could open the inventory for a split second before it closed again)... so I restarted Minecraft, tried entering a different world - THAT was fine. Going back into the one with the problem caused everything to warp and jitter around weirdly visually, though that may have had something to do with another mod or something that was triggering an event in the world when I crafted my wand.

Then eventually I crashed completely, with the log pointing towards Tainted Magic as the culprit. I checked the Github issues for the project, and it seems that other people have had issues with crafting wands as well. Not sure if it's been fixed or how to fix it beyond tweaking in MineTweaker.

And here is my full Minecraft log, should you need it.

http://paste.ee/p/N2Czs

Note: I also had to remove a duplicate Floating Ruins file in order to get Minecraft to run, and I deleted Inventory Tweaks because that mod annoys me to no end(I keep accidentally rearranging my inventory and I'm not sure how to make it stop doing that), but other than that I didn't modify any of the files.

**Comment by Shadows-of-Fire** [comment]
This was fixed in v2.1.0 which should have been approved early this morning.

**Comment by Shadows-of-Fire** [comment]
As for actually removing the corrupted wand, you may be able to remove tainted magic and drop it then reinstall the mod.  Unless you know how to nbt edit it out yourself

**Comment by Shadows-of-Fire** [comment]
As to what actually happens, your player is technically dead while holding that corrupted wand.  Apparently Tainted Magic requires the declaration of cap: iron and rod: wood in minetweaker even though Minetweaker didn't report it with mt hand.

**Comment by Febilian** [comment]
Okay, I will try the new version after figuring out how to get rid of the wand that's causing issues. On a side note, another thing I noticed but forgot to mention last night(I was tired haha) was that putting a piece of normal dirt in a crafting grid resulted in a ridiculously overpowered wand. I didn't actually take the output, as I figured it was a debug recipe of some sort, but there you go.

**Comment by Shadows-of-Fire** [comment]
Yeah, that's a debug recipe that looks like it wasn't removed in copying over the files.

**Comment by Shadows-of-Fire** [comment]
Fixed in v2.2
