### ISSUE TITLE
Custom Stuff 3 apparently required to launch, not found

### ISSUE THREAD

**Issue by Febilian** [Shadows-of-Fire/Magic-Theory-2#3]
https://gyazo.com/f774f92e2583cdbd4b1d12b263447c42

Oddly enough, checking the relevant log file doesn't seem to have any info pertaining to it, but I'll send it anyways.

https://paste.ee/p/1joXw

**Comment by Febilian** [comment]
Okay, so I'm re-downloading the pack fresh to compare the files, seems like just updating the pack left behind some files that aren't used anymore but are still being read by the game. Do you have a note anywhere indicating that existing users would need to delete these files when updating?

**Comment by Shadows-of-Fire** [comment]
I didn't realize it was a problem.  This is once again, FTB's fault.  Their launcher wants to inject any .class file found into minecraft, hence why I couldn't use CS3.

**Comment by Shadows-of-Fire** [comment]
There is a note on the forum post.
