### ISSUE TITLE
Binnie's Mods Issue

### ISSUE THREAD

**Issue by petergao96** [Shadows-of-Fire/Magic-Theory-2#5]
There is a crash when I try to search charcoal's usage via NEI and its reproducible. It states that it is an array out of bounds exception.

[2016-06-10-3.log.gz](https://github.com/Shadows-of-Fire/Magic-Theory-2/files/309759/2016-06-10-3.log.gz)

**Comment by Shadows-of-Fire** [comment]
According to Reika's team, it isn't their fault.  @Binnie567 has vanished, so theres no fixing it there.  Last I saw this error, removing Binnie's makes it a Thaumic NEI plugin error, and removing that fixes it.

**Comment by petergao96** [comment]
Alright, thanks. I guess I'll just avoid charcoal searching then.

**Comment by petergao96** [comment]
Actually, and this is off book, I found that the binnie patcher the mod pack is using is out of date. I replaced it with the version 1.8 and charcoal no longer crashes.

**Comment by Shadows-of-Fire** [comment]
Well, looks like chocohead fixed it.  I'll update it for v3.  I'm doing some major restructuring for world load and biome dependence due to chroma

**Comment by petergao96** [comment]
ty!
